const VEHICLE_CATEGORIES = Object.freeze({
    SEDAN: "SEDAN",
    SUV: "SUV",
    HATCHBACK: "HATCHBACK",
    TRUCK: "TRUCK",
    COUPE: "COUPE",
    CONVERTIBLE: "CONVERTIBLE",
    VAN: "VAN",
    WAGON: "WAGON",
    CROSSOVER: "CROSSOVER"
});

module.exports = VEHICLE_CATEGORIES;